- name: Configure OS parameters
  shell: |
    swapoff /swapfile || fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile

- name: Install utils
  shell: |
    apt install -y zip unzip nano

- name: Install php
  shell: |
    add-apt-repository -y ppa:ondrej/php
    apt update
    apt install -y php8.2 php8.2-cli php8.2-bz2 php8.2-curl php8.2-mbstring php8.2-intl php8.2-xml php8.2-sqlite3
    apt install -y php8.2-fpm

- name: Install MySQL
  shell: |
    apt install -y mysql-server
    systemctl start mysql
    mysql -e "CREATE DATABASE tmpdb /*\!40100 DEFAULT CHARACTER SET utf8 */;"
    mysql -e "CREATE USER user1@localhost IDENTIFIED BY '123456';"
    mysql -e "GRANT ALL PRIVILEGES ON tmpdb.* TO 'user1'@'localhost';"
    mysql -e "FLUSH PRIVILEGES;"
    systemctl restart mysql

- name: Install nginx
  shell: |
    apt install -y nginx
    systemctl stop apache2 || true

- name: Copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Prepare project
  shell: |
    mkdir -p /data/site/public

- name: Copy site data
  copy:
    src: index.php
    dest: /data/site/public/index.php

- name: Enable services
  shell: |
    systemctl enable nginx
    systemctl enable mysql
    systemctl restart nginx
